### PR TITLE
[outline] Fix .Release.Name access in range

### PR DESCRIPTION
**Pull request by Morishiri**

### CODE REVIEW

**Comment by geoah** [comment]
Would be lovely if this could get merged :D

**Comment by Morishiri** [comment]
@nushkovg Sorry for direct mention, but maybe you could take a look?

**Review by nushkovg — CHANGES_REQUESTED** [review]
@Morishiri @geoah I really need to fix my notifications, sorry for the delay, I just saw this. The CI/CD will fail if the version is not bumped though, so please update the `Chart.yaml` version for `outline`  to `1.0.1` and I will merge this (yes, the pipeline needs some automation impovements haha).

**Comment by nushkovg** [comment]
@Morishiri @geoah Disregard my previous comment, I did the update myself in #15, so no worries, the fix is available in version `1.0.1` (my way of saying sorry for waiting so long).

**Pull request closed without merging**
